plugins {
    id 'com.android.application'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.buildinat.test'
    compileSdk 35

    defaultConfig {
        applicationId 'com.buildinat.test'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        debug {
        }

        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
